# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил(а):
- Чередников Максим Евгеньевич
- ИНО ЗБ ПОАС 22-1

| Задание | Сам_раб |
| ------ | ------ | 
| Задание 1 | + |
| Задание 2 | + |
| Задание 3 | + |
| Задание 4 | + |
| Задание 5 | + |


знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Самостоятельная работа №1
- Текст задания: Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.
- Оформленный код: 
```python
import time

def calc_time(func):
    def wrapper():
        start = time.time()
        func()
        end = time.time()

        res = end - start
        print(f"\nВремя выполнения: {res} секунд!" )
        return func
    
    return wrapper

@calc_time
def fibonacci():
    fib1 = fib2 = 1

    for _ in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=" ")


if __name__ == "__main__":
    fibonacci()
```
- Скрины консоли:<br> ![Меню](https://github.com/koiiok97/pi2024/blob/Tema_10/t9/1.png)


## Самостоятельная работа №2
- Текст задания: Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.
- Оформленный код: 
```python
try:
    with open("f2.txt", "r") as file:
        data = file.read()
        
        if not data:
            raise Exception("файл пустой")
        
        print(f"Информация из файла:\n{data}")
        
except Exception as e:
    print("Ошибка:", e)
```
- Скрины консоли:<br> ![Меню](https://github.com/koiiok97/pi2024/blob/Tema_10/t9/2.png)

  
## Самостоятельная работа №3
- Текст задания: Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль
- Оформленный код: 
```python
def sumNumbers():
    try:
        num = float(input("Введите число: "))
        
        print("Результат сложения:", num + 2)
        
    except ValueError:
        print("Ошибка: Неподходящий тип данных. Ожидалось число.")

sumNumbers()
```
- Скрины консоли:<br> ![Меню](https://github.com/koiiok97/pi2024/blob/Tema_10/t9/3.png)


## Самостоятельная работа №4
- Текст задания: Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.
- Оформленный код: 
```python
class Log:
    def __init__(self, func):
        self.func = func
    
    def __call__(self, *args, **kwds):
        print(f"Аргументы: {args}")
        res = self.func(*args, **kwds)
        print("Результат: ", res)

        return res

@Log
def sumNum(*args):
    res = sum(args)
    return res
@Log
def mult(*args):
    res = 1
    for n in args:
        res *= n
    return res

sumNum(2,3,5)
mult(2, 5, 12, 4, 5)
```
- Скрины консоли:<br> ![Меню](https://github.com/koiiok97/pi2024/blob/Tema_10/t9/4.png) 


## Самостоятельная работа №5
- Текст задания: Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода
- Оформленный код: 
```python
class MyException(Exception):
    def __init__(self, mes):
        self.mes = mes


try:
    user = float(input("Введите положительно число: "))

    if user < 0:
        raise MyException("Число не соотвествует условию")
    else:
        print(f"Верно! Введено число: {user}")

except Exception as e:
    print("Ошибка", e)
```

- Скрины консоли:<br> ![Меню](https://github.com/koiiok97/pi2024/blob/Tema_10/t9/5.png)


